# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Open Education Working Group
email: bestuur@studentinnovations.org
phone: +32 495317301
description: > # this means to ignore newlines until "baseurl:"
  De Open Education Working Group heeft als doel de informatisering van het onderwijs te bevorderen en open data te promoten.
baseurl: "/open-education/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: openknowledgebe/open-education

# Build settings
markdown: kramdown
theme: minima
gems:
#  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Translations
#lang: nl
t:
  nl:
    contact_us: "Contacteer Ons"
    name: "Naam"
    email: "E-mail"
    message: "Bericht"
    send_message: "Verstuur Bericht"
    phone: "Telefoon"
    our_partners: "Onze partners"
    message_sent: "Bericht verzonden"
    message_sent_message: "Uw bericht werd verzonden. Wij antwoorden hierop zo snel als we kunnen."
    slogan: "Open data, open geesten"
  en:
    contact_us:  "Contact Us"
    name: "Name"
    email: "E-mail"
    message: "Message"
    send_message: "Send Message"
    phone: "Phone"
    our_partners: "Our partners"
    message_sent: "Message sent"
    message_sent_message: "Your message has been sent. We will reply as soon as possible."
    slogan: "Open data, open minds"